/* tslint:disable */
require("./CloudPlatform.module.css");
const styles = {
  cloudPlatform: 'cloudPlatform_f0fb9fa6',
  hero: 'hero_f0fb9fa6',
  heroContent: 'heroContent_f0fb9fa6',
  breadcrumb: 'breadcrumb_f0fb9fa6',
  heroTitle: 'heroTitle_f0fb9fa6',
  heroIcon: 'heroIcon_f0fb9fa6',
  heroSubtitle: 'heroSubtitle_f0fb9fa6',
  heroStats: 'heroStats_f0fb9fa6',
  statCard: 'statCard_f0fb9fa6',
  statValue: 'statValue_f0fb9fa6',
  statLabel: 'statLabel_f0fb9fa6',
  mainContent: 'mainContent_f0fb9fa6',
  sidebar: 'sidebar_f0fb9fa6',
  sidebarTitle: 'sidebarTitle_f0fb9fa6',
  sidebarNav: 'sidebarNav_f0fb9fa6',
  navItem: 'navItem_f0fb9fa6',
  active: 'active_f0fb9fa6',
  navIcon: 'navIcon_f0fb9fa6',
  navDivider: 'navDivider_f0fb9fa6',
  contentArea: 'contentArea_f0fb9fa6',
  sectionCard: 'sectionCard_f0fb9fa6',
  sectionHeader: 'sectionHeader_f0fb9fa6',
  sectionTitle: 'sectionTitle_f0fb9fa6',
  icon: 'icon_f0fb9fa6',
  sectionAction: 'sectionAction_f0fb9fa6',
  sectionContent: 'sectionContent_f0fb9fa6',
  quickStats: 'quickStats_f0fb9fa6',
  quickStat: 'quickStat_f0fb9fa6',
  quickStatIcon: 'quickStatIcon_f0fb9fa6',
  quickStatValue: 'quickStatValue_f0fb9fa6',
  quickStatLabel: 'quickStatLabel_f0fb9fa6',
  docGrid: 'docGrid_f0fb9fa6',
  docCard: 'docCard_f0fb9fa6',
  docIcon: 'docIcon_f0fb9fa6',
  xlsx: 'xlsx_f0fb9fa6',
  pdf: 'pdf_f0fb9fa6',
  docx: 'docx_f0fb9fa6',
  pptx: 'pptx_f0fb9fa6',
  ps1: 'ps1_f0fb9fa6',
  docInfo: 'docInfo_f0fb9fa6',
  docName: 'docName_f0fb9fa6',
  docMeta: 'docMeta_f0fb9fa6',
  externalLinks: 'externalLinks_f0fb9fa6',
  externalLink: 'externalLink_f0fb9fa6',
  linkIcon: 'linkIcon_f0fb9fa6',
  loading: 'loading_f0fb9fa6',
  loadingMessage: 'loadingMessage_f0fb9fa6',
  emptyState: 'emptyState_f0fb9fa6',
  footer: 'footer_f0fb9fa6'
};

export default styles;
/* tslint:enable */